Added few datapack faqs
SheepCommander/KnowledgeBase pull request #1
Opened 2020-10-27 19:01 UTC by Zefyro

what do you think of this?

2020-10-27 19:09 UTC, SheepCommander requested changes
Nice but I think we'll have downloadable templates in the repository instead and use the Wiki for both raw pastes and also a readable version

2020-10-28 16:46 UTC, MMK21Hub reviewed
Sooks good, but I feel like it would make sense to get the layout guidelines decided upon first. (#2)

2020-10-28 16:46 UTC, MMK21Hub commented on Resources/faqs/datapacks/Code to go in pack.mcmeta/example pack.mcmeta.mcmeta
> +}
Not sure why there needs to be a separate file for this?

2020-10-28 16:46 UTC, MMK21Hub commented on Resources/faqs/datapacks/Code to go in pack.mcmeta/pack.mcmeta description.txt
> +6 = 1.16.2
Since this is the `Resources` dir, it would make more sense to make this a Markdown file?

2020-10-28 16:46 UTC, MMK21Hub commented on Resources/faqs/datapacks/What do I put in tag.json (DP) (JE) (1.13+)/example 'tag'.json.json
> +}
Again, not sure why there needs to be a separate file for this

2020-10-28 16:46 UTC, MMK21Hub commented on Resources/faqs/datapacks/What do I put in tag.json (DP) (JE) (1.13+)/tag.json description.txt
> +This can be used for tick.json/load.json, or for Block tags and other
Convert this to MD too?

2020-11-11 02:32 UTC, SheepCommander commented
We've set up a list of things to do, try following that instead

2020-11-11 02:32 UTC, closed without merging